### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by MohamedAbdallah-14** [Leocardoso94/flutter-countdown#8]
I have Submitted PR to migrate to null safety #7

**Comment by anilraok** [comment]
+1

**Comment by AntiDesert5** [comment]
```
dependencies:
  countdown_flutter:
    git:
      url: https://github.com/MohamedAbdallah-14/flutter-countdown.git
      ref: Migrate-to-null-safety
```
